services:
  db:
    image: postgres:15
    container_name: tc5_fiap_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

  web:
    build: .
    container_name: tc5_fiap_web
    command: gunicorn tc5_fiap.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD:
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data: